"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.sycamore = exports.celery = exports.portica = exports.equator = exports.tahiti = exports.flamingo = exports.razzmatazz = exports.havelockBlue = exports.cadetBlue = exports.hunterGreen = exports.blackOlive = exports.logCabin = exports.rifleGreen = exports.oliveDrab = exports.sushi = exports.citron = exports.woodsmoke = exports.tuatara = exports.emperor = exports.stormDust = exports.hurricane = exports.stardust = exports.gainsborough = exports.bonjour = exports.springWood = void 0;
var springWood = "#f8f6f1";
exports.springWood = springWood;
var bonjour = "#e5e0e1";
exports.bonjour = bonjour;
var gainsborough = "#d5d8d2";
exports.gainsborough = gainsborough;
var stardust = "#9f9f9c";
exports.stardust = stardust;
var hurricane = "#908989";
exports.hurricane = hurricane;
var stormDust = "#646463";
exports.stormDust = stormDust;
var emperor = "#515150";
exports.emperor = emperor;
var tuatara = "#363534";
exports.tuatara = tuatara;
var woodsmoke = "#0c0d0f";
exports.woodsmoke = woodsmoke;
var citron = "#86b923";
exports.citron = citron;
var sushi = "#7fa82f";
exports.sushi = sushi;
var oliveDrab = "#638829";
exports.oliveDrab = oliveDrab;
var rifleGreen = "#414833";
exports.rifleGreen = rifleGreen;
var logCabin = "#24301d";
exports.logCabin = logCabin;
var blackOlive = "#1c2412";
exports.blackOlive = blackOlive;
var hunterGreen = "#161d10";
exports.hunterGreen = hunterGreen;
var cadetBlue = "#5f9ea0";
exports.cadetBlue = cadetBlue;
var havelockBlue = "#5B8De1";
exports.havelockBlue = havelockBlue;
var razzmatazz = "#e3256b";
exports.razzmatazz = razzmatazz;
var flamingo = "#f34b44";
exports.flamingo = flamingo;
var tahiti = "#F58A0A";
exports.tahiti = tahiti;
var equator = "#e4aC5e";
exports.equator = equator;
var portica = "#f7e75f";
exports.portica = portica;
var celery = "#bcb852";
exports.celery = celery;
var sycamore = "#908d39";
exports.sycamore = sycamore;