"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.TEMPLATE_LITERAL_DELIMITER_CONTENT = exports.GUTTER_HEIGHT = exports.BOTTOM_SIDE = exports.RIGHT_SIDE = exports.LEFT_SIDE = exports.TOP_SIDE = exports.DEFAULT_HOST = exports.VARIABLE_TYPE = exports.PLAIN_TEXT_LANGUAGE = exports.JAVASCRIPT_LANGUAGE = exports.JSON_LANGUAGE = exports.XML_LANGUAGE = void 0;
var XML_LANGUAGE = "xml";
exports.XML_LANGUAGE = XML_LANGUAGE;
var JSON_LANGUAGE = "json";
exports.JSON_LANGUAGE = JSON_LANGUAGE;
var JAVASCRIPT_LANGUAGE = "javascript";
exports.JAVASCRIPT_LANGUAGE = JAVASCRIPT_LANGUAGE;
var PLAIN_TEXT_LANGUAGE = "plain-text";
exports.PLAIN_TEXT_LANGUAGE = PLAIN_TEXT_LANGUAGE;
var VARIABLE_TYPE = "variable";
exports.VARIABLE_TYPE = VARIABLE_TYPE;
var DEFAULT_HOST = "";
exports.DEFAULT_HOST = DEFAULT_HOST;
var TOP_SIDE = "top";
exports.TOP_SIDE = TOP_SIDE;
var LEFT_SIDE = "left";
exports.LEFT_SIDE = LEFT_SIDE;
var RIGHT_SIDE = "right";
exports.RIGHT_SIDE = RIGHT_SIDE;
var BOTTOM_SIDE = "bottom";
exports.BOTTOM_SIDE = BOTTOM_SIDE;
var GUTTER_HEIGHT = "100000px";
exports.GUTTER_HEIGHT = GUTTER_HEIGHT;
var TEMPLATE_LITERAL_DELIMITER_CONTENT = "`";
exports.TEMPLATE_LITERAL_DELIMITER_CONTENT = TEMPLATE_LITERAL_DELIMITER_CONTENT;